name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  run_unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      # checkpout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      # Install dependencies and run tests
      - name: Install dependencies
        run: |
          cd app
          npm install
      - name: Run tests
        run: |
          npm test
